### ISSUE TITLE
how to implement the visualization for the learned edges?

### ISSUE THREAD

**Issue by micklexqg** [ewrfcas/MST_inpainting#9]
hello, thanks for your nice work. I have a question, as I do not find the related codes in the downloaded package, I wonder how to implement the visualization for the learned edges such as the blue edge.
![image](https://user-images.githubusercontent.com/13776012/202632520-ea768ef1-9d66-4d17-8cda-5b1a36416d8d.png)

besides, what are the selected  10 Places2 classes for P2C?

**Comment by ewrfcas** [comment]
Hi，
1) Since edge regions are 255 and the background is 0, you can try to set the red channel (in RGB) to 0 as:
Edge_blue = Edge.copy()
Edge_blue[:,:,0] = 0

Then combine the mask and unmasked regions of edges as:
Edge_combine = Edge*(1-mask) + Edge_blue * mask


2) We trained on ‘balcony-exterior’, ‘computer-room’, ‘embassy’, ‘galley’, ‘general-store-outdoor’, ‘home-office’, ‘kitchen’, ‘library-outdoor’, ‘parking-garage-outdoor’, and ‘shopfront’. We have listed these in the supplementary.

**Comment by micklexqg** [comment]
@ewrfcas Thanks!
